// Generated by CoffeeScript 1.9.3
(function() {
  var Brain, util;

  util = require('util');

  Brain = (function() {
    function Brain(nicknames, bot, loadCB) {
      this.nicknames = nicknames;
      this.bot = bot;
      this.loadCB = loadCB;
      if (this.loadCB) {
        this.loadCB();
      }
    }

    Brain.prototype.react = function(channel, who, msg) {
      var delayed;
      delayed = true;
      return this.bot.respond(channel, who + " said " + msg, delayed);
    };

    return Brain;

  })();

  module.exports = Brain;

}).call(this);
