// Generated by CoffeeScript 1.9.3
(function() {
  var Brain, util;

  util = require('util');

  Brain = (function() {
    function Brain(bot) {
      this.bot = bot;
    }

    Brain.prototype.react = function(channel, who, msg) {
      var delayed;
      delayed = true;
      return this.bot.respond(channel, who + " said " + msg, delayed);
    };

    return Brain;

  })();

  module.exports = Brain;

}).call(this);
