// Generated by CoffeeScript 1.9.3
(function() {
  var Skittles, fs, main, util;

  fs = require('fs');

  util = require('util');

  Skittles = require('./skittles');

  main = function() {
    var settings, skittles;
    settings = {};
    if (fs.existsSync("settings.json")) {
      util.log("Reading settings.json");
      settings = JSON.parse(fs.readFileSync("settings.json"));
    } else {
      util.log("settings.json not found, using defaults");
    }
    return skittles = new Skittles(settings);
  };

  module.exports = {
    main: main
  };

}).call(this);
