// Generated by CoffeeScript 1.9.3
(function() {
  var Skittles, defaultSettings, irc, util;

  irc = require('irc');

  util = require('util');

  defaultSettings = {
    host: 'localhost',
    port: 6667,
    nicknames: ['Skittles'],
    channels: ['#test']
  };

  Skittles = (function() {
    function Skittles(settings) {
      var name, value;
      this.settings = settings;
      for (name in defaultSettings) {
        value = defaultSettings[name];
        if (!this.settings.hasOwnProperty(name)) {
          this.settings[name] = value;
        }
      }
      util.log("using settings:\n" + JSON.stringify(this.settings, null, 2));
      this.createClient();
    }

    Skittles.prototype.createClient = function() {
      return this.client = new irc.Client(this.settings.host, this.settings.nicknames[0], {
        channels: this.settings.channels
      });
    };

    return Skittles;

  })();

  module.exports = Skittles;

}).call(this);
